FROM debian:jessie-slim
MAINTAINER Joshua Barber "j.barber501@gmail.com"

USER root

# Install basic system packages and add /bin/bash as default shell
RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
        openssh-server \
        python3-dev \
        python3-wheel \
        build-essential \
        apt-utils \
        wget \
        git \
        bzip2 \
        ca-certificates \
        sudo \
        locales \
        pandoc \
        libsm6 \
        libxrender1 \
        libpq-dev \
        swig && \
    rm /bin/sh && ln -s /bin/bash /bin/sh

# Install Tini
RUN wget --quiet https://github.com/krallin/tini/releases/download/v0.10.0/tini && \
    echo "1361527f39190a7338a0b434bd8c88ff7233ce7b9a4876f3315c22fce7eca1b0 *tini" | sha256sum -c - && \
    mv tini /usr/local/bin/tini && \
    chmod +x /usr/local/bin/tini

# Set environment variables
ENV CONDA_DIR=/opt/conda
ENV PATH=/$CONDA_DIR/bin:${PATH}
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Miniconda PY3 v4.2.12 installation
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh && \
    /bin/bash Miniconda3-4.2.12-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-4.2.12-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda config --system --add channels conda-forge && \
    $CONDA_DIR/bin/conda config --system --set auto_update_conda false && \
    conda clean -tipsy

WORKDIR /home

# Configure container startup
ENTRYPOINT ["/usr/local/bin/tini", "--"]